name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Formatting
      uses: github/super-linter@v3
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_SNAKEMAKE_SNAKEFMT: true

  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Linting
      uses: snakemake/snakemake-github-action@v1.14.0
      with:
        directory: '.test'
        snakefile: 'Snakefile'
        args: '--lint'

  run-workflow:
    runs-on: ubuntu-latest
    needs:
      - formatting
      - linting
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    
    - name: snakemake
      uses: snakemake/snakemake-github-action@v1.14.0
      with:
        directory: .test
        snakefile: Snakefile
        args: "--use-conda --show-failed-logs --cores 1 --conda-cleanup-pkgs cache"

